#include <stdio.h>
#include <stdlib.h>
#include <time.h>

// Partition using last element as pivot (after randomization)
int partition(int* arr, int low, int high) {
    // Step 1: Randomly select pivot and swap with last
    int randomPivotIndex = low + rand() % (high - low + 1);
    int temp = arr[randomPivotIndex];
    arr[randomPivotIndex] = arr[high];
    arr[high] = temp;

    // Step 2: Usual Lomuto partition with arr[high] as pivot
    int pivot = arr[high];
    int i = low - 1;

    for (int j = low; j < high; j++) {
        if (arr[j] <= pivot) {
            i++;
            // Swap arr[i] and arr[j]
            temp = arr[i];
            arr[i] = arr[j];
            arr[j] = temp;
        }
    }

    // Swap arr[i + 1] and arr[high] (pivot)
    temp = arr[i + 1];
    arr[i + 1] = arr[high];
    arr[high] = temp;

    return i + 1;
}

// Recursive QuickSort
void quickSort(int* arr, int low, int high) {
    if (low < high) {
        int pivotIndex = partition(arr, low, high);
        quickSort(arr, low, pivotIndex - 1);
        quickSort(arr, pivotIndex + 1, high);
    }
}

int main() {
    int *arr = NULL, len;

    // Seed RNG only once
    /**
     * srand(time(NULL)) seeds the random number generator in C using the current time. The srand function initializes the random number generator, and time(NULL) provides the current time in seconds since the Unix epoch. This ensures that the sequence of pseudo-random numbers generated by rand() will likely be different each time the program runs. If srand is not called, rand produces the same sequence of numbers every time the program runs. 
     */
    srand(time(NULL));

    printf("Enter count of elements in the array: ");
    scanf("%d", &len);

    arr = (int *)malloc(len * sizeof(int));
    if (arr == NULL) {
        fprintf(stderr, "Memory allocation failed.\n");
        exit(1);
    }

    for (int i = 0; i < len; i++) {
        printf("Enter element at position %d: ", i + 1);
        scanf("%d", &arr[i]);
    }

    quickSort(arr, 0, len - 1);

    printf("\nSorted array: ");
    for (int i = 0; i < len; i++) {
        printf("%d ", arr[i]);
    }
    printf("\n");

    free(arr);
    return 0;
}
